### ISSUE TITLE
Is creepminer closing file handles?

### ISSUE THREAD

**Issue by Axadiw** [Creepsky/creepMiner#103]
Hi,

I'm using creepminer with plotfiles that are stored on Amazon Cloud Drive service, that I'm accessing using *acd_cli* software: https://github.com/yadayada/acd_cli

The problem I was experiencing was huuge memory consumption caused by *acd_cli*. That's why I've submitted an issue on their repository about it: https://github.com/yadayada/acd_cli/issues/551

They are assuming that creepminer isn't closing file handles for plotfiles. Did they found an issue on creepminer, or maybe something else is causing this memory consumption?

**Comment by Creepsky** [comment]
Hmm, interesting issue.

The miner closes the files [manually](https://github.com/Creepsky/creepMiner/blob/master/src/PlotReader.cpp#L175) after they got read or the next block begins.
However it should not matter, because the c++ file-stream gets [automatically](http://www.cplusplus.com/reference/fstream/fstream/close/) closed when the object gets destroyed.

Maybe the memory consumption comes from the interaction of the miner and acd_cli.

One thing you could do is to look at the open files with the command [lsof](https://www.ibm.com/developerworks/aix/library/au-lsof.html).

**Comment by Axadiw** [comment]
I've checked with *lsof*, and it looks like indeed, creepiner is closing file handles properly, so it probably might be an *acd_cli* issue
