### ISSUE TITLE
Keeping scoops locally, rest remotely

### ISSUE THREAD

**Issue by Axadiw** [Creepsky/creepMiner#104]
Hey,

I've came up with crazy idea: 

During mining process, every block (every ~4 minutes), creepminer is reading only 1/4096 of all plotfiles, right? From what I've read it's reading only scoops of whole plotfile.

Than, when miner finds correct scoop, that it reads rest of found nonce, and sends it to the pool.

So, in case when you're using remote storage, right now I'm storing all plotfiles remotely, and every block I have to download shitloads of data, just to check those scoops.

Because I have locally couple of GBs of free space I could just store scoops of my plotfiles locally, and search them every block, instead of downloading them over and over again every block.

So in the end, would it be possible to creat some kind of program that will extract those scoops out of plotted files, and than force creepminer somehow to check only those? In case of matching block, creepminer would download it from remote site.

**Comment by Creepsky** [comment]
Hi,

interesting idea and in theory you are right. But there is a little problem with storing only one scoop locally. Every round, a random scoop from 1-4096 is chosen by the burst network that has to be scanned by the miners.
So when you just store one scoop, you have to be really lucky (1/4096 chance) to catch the right scoop.

However, it should be possible to stream only the needed data from the remote repository by skipping the other 4095 scoops from every nonce.

Is there any possibility to download a specific area from the files by determining it in the tool you are using?
If yes, it would be easy to create some kind of plugin for the creepminer.

**Comment by Axadiw** [comment]
hmm, 

Maybe I don't understand something, but I wanted to store locally all the data that is beeded during seeking process (until miner would find forrect nonce to submit).

What exactly is creepminer reading during mining process? 
For example if I would have 100TB in single plotfile, how much would of it would be read by the miner?

And by the way - it is possible to download only certain part of the remote file. I'm using `https://github.com/yadayada/acd_cli` for mounting, that is creating FUSE filesystem for ACD drives.

**Comment by Creepsky** [comment]
The mining process is:
1.) get the scoop for the current block (1-4096)
2.) read the scoop from every nonce in the plot files
3.) check deadlines (and submit)

Scoop: 64 Byte
Nonce: 4096 Scoops = 256 kByte

The miner reads only 1/4096 of all plot files, so with 100TB it would read 419430400 nonces, each 1 scoop with 64 byte = 25GB.

![tmp](https://cloud.githubusercontent.com/assets/8005422/26034284/ad81ef82-38ba-11e7-80f2-9cc80296aed9.png)

It is sufficient to download only the current scoop for all nonces. The problem with this would be, that the miner would assume a wrong intern structure of the file. This could be fixed by renaming the files:

from ```<account_id>_<start_nonce>_<nonces>_<stagger>```
to ```<account_id>_<start_nonce>_<nonces>_<nonces>``` (so in the end what you do is a "on-the-fly-optimization")

How exactly is **acd_cli** working? Is it downloading the files on access, or do you need an extern script?
And if it is downloading on access, is it downloading only the needed data (because the miner is skipping all the unnecessary data) or the whole file?

**Comment by Creepsky** [comment]
@Axadiw do you still have this issue?
Blago came up with a very good idea that would fix your problem:
https://forums.burst-team.us/topic/5823/network-drives-windows.

It means some work for plotter + miner, but is not impossible to do.
