### ISSUE TITLE
Warning: illegal character encoding in string literal

### ISSUE THREAD

**Issue by k06a** [Creepsky/creepMiner#128]
What do you think about following warning? Looks like non UTF-8 character occurred in source code file.
```
creepMiner/src/MinerUtil.cpp:317:30: warning: illegal character encoding in string literal [-Winvalid-source-encoding]
                validChars += "()[]*/+-#'~?<B4>`&$!";
                                           ^~~~
```

**Comment by Creepsky** [comment]
You are right, had some issues with it too and fixed it in this commit here 23a6031e4517589cb47eafe0f98ca95b4b16319a: https://github.com/Creepsky/creepMiner/blob/webserver-rework/src/MinerUtil.cpp#L339.
But it for another branch and should be cherry-picked into development, because I think the webserver-rework will take some more time.

**Comment by k06a** [comment]
Fine

**Comment by Creepsky** [comment]
Ok, done: 347dd6b77fb706bcf2131d98fb806a970c165331
