### ISSUE TITLE
ArchLinux (Manjaro Linux) someone who builded from source ?

### ISSUE THREAD

**Issue by NikolaPavlov** [Creepsky/creepMiner#152]
Is there anyone willing to help me to build on arch(manjaro)? Yaourt package will be great future!

**Comment by ITwrx** [comment]
@NikolaPavlov have you tried downloading the ubuntu tarball, extracting it and running it? i think it will work fine with arch. i just tried and it ran. i didn't have actualplots configured or anything but the script did run.

**Comment by NikolaPavlov** [comment]
Thx for helping ITwrx. Recived this error when ./run.sh:

`./run.sh: line 4: 25254 Illegal instruction     (core dumped) ./creepMiner
`

**Comment by Creepsky** [comment]
Why dont you try to follow the [compile instructions in the wiki](https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation)?

The steps are the same,

1 install openssl
1. download and compile poco
2. download and compile miner

Only thing you need to change is the install_poco script by replacing all debian commands with arch linux commands (use pac instead of apt).

**Comment by ITwrx** [comment]
i'm going to assume you already have openssl installed on your system because it's so ubiquitous. If not, install it. 

but maybe you don't have poco installed? 

"pacman -S poco". 

then try again.

**Comment by NikolaPavlov** [comment]
Creepsky i tried to compile, tried really hard :( 
1. Install openssl (check)
2. Download and compile poco
Error when compiling:

> src/CipherImpl.cpp:80:21: error: field ‘_ctx’ has incomplete type ‘EVP_CIPHER_CTX {aka evp_cipher_ctx_st}’
   EVP_CIPHER_CTX    _ctx;
                     ^~~~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from include/Poco/Crypto/OpenSSLInitializer.h:26,
                 from include/Poco/Crypto/CipherKeyImpl.h:24,
                 from include/Poco/Crypto/CipherKey.h:24,
                 from include/Poco/Crypto/CipherImpl.h:25,
                 from src/CipherImpl.cpp:17:
/usr/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
 typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                ^~~~~~~~~~~~~~~~~
make[1]: *** [/home/gogo/Mining/Temp/POCO/poco-1.7.6-all/build/rules/compile:54: /home/gogo/Mining/Temp/POCO/poco-1.7.6-all/Crypto/obj/Linux/x86_64/debug_shared/CipherImpl.o] Error 1
make[1]: Leaving directory '/home/gogo/Mining/Temp/POCO/poco-1.7.6-all/Crypto'
make: *** [Makefile:201: Crypto-libexec] Error 2
2. Install POCO from arch community repo: Poco 1.7.8.3-4 (check)
3. Compile miner
Error while 'make': 
>g++ -O3 -march=native -std=c++14 -Wall -D_REENTRANT -DNDEBUG -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/sphlib/sph_shabal.cpp -o bin/obj/sphlib/sph_shabal.o
g++ -O3 -march=native -std=c++14 -Wall -D_REENTRANT -DNDEBUG -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/nxt/nxt_address.cpp -o bin/obj/nxt/nxt_address.o
g++ -O3 -march=native -std=c++14 -Wall -D_REENTRANT -DNDEBUG -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/Url.cpp -o bin/obj/Url.o
In file included from src/Url.cpp:2:0:
src/MinerLogger.hpp:125:68: error: ‘std::function’ has not been declared
   static void writeAndFunc(Burst::MinerLogger::TextType type, std::function<void()> func);
                                                                    ^~~~~~~~
src/MinerLogger.hpp:125:76: error: expected ‘,’ or ‘...’ before ‘<’ token
   static void writeAndFunc(Burst::MinerLogger::TextType type, std::function<void()> func);

**Comment by ITwrx** [comment]
now, that you installed poco, why not try running the ubuntu download(run.sh) again?

**Comment by Creepsky** [comment]
Your compilation errors should be fixed in the development branch.
If run.sh will not work, download the development branch and try it again.

You will notice that there is one additional step that you have to do -> [create your makefile with cmake](https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-with-CMake).

**Comment by jant90** [comment]
On Manjaro you can conveniently install the poco package using pacman so you don't have to compile poco yourself. Then you just need to pull the git repo from development branch and run cmake and make. That last part confused me a bit because before a Makefile was included and thus it was not necessary to run cmake first.

Anyways, if you want it easy:
```
pacman -S poco
git clone -b development https://github.com/Creepsky/creepMiner.git
cd creepMiner
cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=RELEASE
make
```
And the creepMiner binary will be in the bin/ subfolder. Check the [possible cmake parameters here first though](https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-with-CMake).

**Comment by NikolaPavlov** [comment]
Thank you all! Successfully compiled from the development branch with the instruction from creepsky.
1. Install openssl
2. Install poco (from pacman)
3. Compile with cmake

**Comment by ronnylov** [comment]
I have built it on Arch Linux.
To be able to compile it I added following line in Account.hpp and in MinerLogger.hpp:
#include <functional>

**Comment by ronnylov** [comment]
I compiled it on Arch Linux after I added include functional in MinerLoccer.hpp and Account.hpp like described here:
http://en.cppreference.com/w/cpp/utility/functional/function

Maybe Arch use C++17?

**Comment by llybin** [comment]
@ronnylov fix build on arch, which has gcc 7.1 on a dev, but dev branch have a performance problems now. U can try to find commit how to fix a build.

**Comment by ronnylov** [comment]
I am not sure how to make a commit if that was your suggestion. Only thing I changed was adding an include line in the two header files MinerLogger.hpp and Account.hpp and then it compiled without errors. I am mining now on Arch Linux.

Add this line:
`#include <functional>`

**Comment by llybin** [comment]
Yes, or use develop version, performance is great now.

**Comment by NikolaPavlov** [comment]
Thanks for help all!
