### ISSUE TITLE
Error: Your deadline is good... for the previous block! You submitted your nonce too late.

### ISSUE THREAD

**Issue by ITwrx** [Creepsky/creepMiner#159]
i was getting these and other errors while mining with burstcoin.biz and didn't get paid for 3 days. i've switched pools now as i thought maybe they were getting ddos'd and i've had no errors with the new pool for a few hours. 

now i get "Error: Your deadline is good... for the previous block! You submitted your nonce too late."

my miner's OS clock is correct and using ntp. is this on my end or the pool?

thanks

**Comment by ITwrx** [comment]
no errors for 1.5 hrs since.

**Comment by Creepsky** [comment]
You should get this error only on a very fast block, when the submission of your nonce intersects with the start of the next block.

The pool checks your deadline that you send for the previous block, but in the in the meantime the next block arrived.

Nothing to worry about, but how often do you get this message? It should be really rare, otherwise something strange is going on.

**Comment by ITwrx** [comment]
ok, thanks. this was the first time with this pool. It was happening fairly often with burstcoin.biz but i think they might have been getting ddos'd or something. i'll keep and eye on it and let you know if it keeps happening.
