### ISSUE TITLE
Limit threads to one per drive

### ISSUE THREAD

**Issue by mrandt** [Creepsky/creepMiner#170]
I would like a feature that allows to have creepMiner run exactly one thread per drive.

Mechanical harddrives are most efficient when files are being read sequentially. Random access requires repositioning the heads and adds seek time. So two or more threads reading files from the same harddrive is 
rather inefficient.

Option 1 would be to sort all plot files by path and group those by common folder:

/Volumes/disk0/plot1
/Volumes/disk0/plot2
/Volumes/disk0/plot3
/Volumes/disk1/plot1
/Volumes/disk1/plot2
/Volumes/disk1/plot3

Evertything that starts with "/Volumes/disk0" should be in one group (one thread) and similarly, everything beginning with "/Volumes/disk1" should be in another.

Option 2 would be manual configuration; just make plot files an array of arrays in config file - but that might be more difficult for people to understand and configure.

I am testing creepMiner on MacOS and also a Linux box and like it a lot so far :-)

BTW: On Windows, Blago Miner does run one thread per drive letter.

**Comment by Creepsky** [comment]
When you set `"maxPlotReaders" : 0"`, the miner will It create exactly as many threads as there are hard disks. 

Plot directories with the same prefix (`/Volumes/disk0` -> drive A, `/Volumes/disk1` -> drive B in your example) will be handled by max. 1 reader, so the miner implements Option 1.



However, on some devices you want random access, because the drive can handle it very fast (SSD for example). Then you can define the plot dir as parallel.
Every plot file inside this drive will be seen as an independ unit.

The syntax for this feature is like this:

```
"plots" : [
    "/media/drive-a", <- traditional way
    {
        "path" : "/media/drive-b", <---- same as above but
        "type" : "sequential"      <---- more verbose
    },
    {
        "path" : "/media/drive-c",
        "type" : "parallel"
    }
]
```
