### ISSUE TITLE
creepMiner-cpu ignores cpuInstructionSet if processorType is OPENCL

### ISSUE THREAD

**Issue by yuzi-co** [Creepsky/creepMiner#215]
20:42:33: Processor type : OPENCL
20:42:33: You are using the processor type OPENCL with the instruction set AVX2,
20:42:33: but your miner is compiled without that feature!
20:42:33: As a fallback solution CPU with SSE2 is used.

Expected behavior: use AVX2

**Comment by Creepsky** [comment]
That was intended in the first place, because SSE2 is the only cpu instruction set that is not optional.
AVX, AVX2 and SSE4 can be disabled by using `USE_AVX=OFF`, `USE_AVX2=OFF` and `USE_SSE4=OFF`.
For example using AVX with a miner where `USE_AVX` is set to `OFF` during compilation would also cause the fallback to SSE2.

I changed this behaviour to a two-step-fallback-solution:
- when processor type is OpenCL or CUDA but compiled without it, fallback to CPU
- when processor type is CPU but compiled without instruction set, fallback to SSE2

So:
>20:42:33: Processor type : OPENCL
>20:42:33: You are using the processor type OPENCL with the instruction set AVX2,
>20:42:33: but your miner is compiled without that feature!
>20:42:33: As a fallback solution CPU with SSE2 is used.
>
>Expected behavior: use AVX2

would be only expected when:
- miner is build without OpenCL
- AND miner is build with AVX2

Otherwise it will again fallback to SSE2.

**Comment by yuzi-co** [comment]
Right, this is logical solution.
I forgot to say that I was using the creepMiner-cpu which supports AVX2 and in OPENCL/AVX2 combination it failed back to SSE2, but you figured that out :)
