### ISSUE TITLE
A plotreader just crashed while reading! Reason: bad allocation.

### ISSUE THREAD

**Issue by utmuk** [Creepsky/creepMiner#287]
creepMiner shows this error on start and continues on mining and the error never shows again, only on start.
<img width="412" alt="a" src="https://user-images.githubusercontent.com/28525658/35440451-82e935f8-02b0-11e8-8e55-4ef0158d03ad.PNG">

**Comment by utmuk** [comment]
creepMiner-win64-1.8.0, Windows 7

**Comment by kruemelone** [comment]
Hi all

I have a similar issue. I've used 1.8.0 and then switched to 1.7.6 on Windows 10 LTSB 2015.

I use two machines in a forwarding construction:
PC A (Info, Submission and Wallet forwarded to PC B) and PC B (qbundle linked to the pool).
PC A has 3 plot files on partition i:\, k:\ and p:\
PC B has 4 disks mounted as ntfs folder under serval paths under k:\

Now: PC A finds a nonce and I can see this info on PC B. PC B tries to read the nonce and submit it to the pool. Shortly after the confirmation, creepminer shows the message: "plotreader just crashed..."

I use creepminer-cpu.exe on bothe machines because it feels faster than the ordinary creepminer.exe.

![miner01 - plotreader crashed](https://user-images.githubusercontent.com/35976118/35593476-450d0292-0610-11e8-8329-89a3d8a5710e.png)

Can't help myself. It should be working.

**Comment by utmuk** [comment]
I played with "maxBufferSizeMB" in config and it possibly helps. I have set it to 500 but I think higher values are also possible. 2500 for example. 0 is default and means automatic.

**Comment by kruemelone** [comment]
Thanks for the tip. I've tried creepminer with /setup mode and recognized, that not only my buffer was the problem but also the plotreader and intensity..
I changed my settings and since then not one plotreader crash. the problem seems to be gone.

**Comment by Creepsky** [comment]
I have created a new FAQ entry for this issue: https://github.com/Creepsky/creepMiner/wiki/FAQ#bad-allocation.

It happens, when the OS can not allocate memory.

**Comment by Creepsky** [comment]
Also fixed in 1.7.16.
