### ISSUE TITLE
The plotfile is incomplete! with creepMiner 1.7.16 Windows x64

### ISSUE THREAD

**Issue by Have-a-question-about-this-project** [Creepsky/creepMiner#324]
I've tried re-plotting this file several times with different options for threads and memory.
Burst PlotsChecker tool says the file is good.
creepMiner 1.7.16 doesn't like it.
Could do with more info in the log file as to what it doesn't like about the plot file.

Microsoft Windows [Version 10.0.16299.248]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\>start /low /b /wait c:\plot\Qbundle\XPlotter\XPlotter_avx.exe -id XXXXXXXX -sn 303269102 -mem 20G -t 12 -path C:\plot\broken -n 6848

XPlotter **v1.0** for BURST
                programmers: Blago, Cerr Janror, DCCT

Checking directory...
Drive c:\ info:
        Name:
        File system: NTFS
        Serial Number: XXX
        FILE_SUPPORTS_SPARSE_FILES: yes
        Bytes per Sector: 512
        Sectors per Cluster: 8
Creating file: c:\plot\broken\XXXXXXXX_303269102_6848_6848
ID:  XXXXXXXX
Start_nonce:  303269102
Nonces: 6848
Nonces per thread:  6848
Uses 3424 Mb of 25138 Mb free RAM
Allocating memory for nonces...  OK
[0%] Generating nonces from 303269102 to 303275950
Closing file...
All done. 219 seconds
Releasing memory...  OK

C:\>C:\plot\PlotsChecker.exe
BURST plots checker (version 1.0)
Checking and validation plots for BURST  [Programming: Blago]
Usage:   PlotsChecker.exe [PATH]
Example:   PlotsChecker.exe d:\plots

C:\>C:\plot\PlotsChecker.exe C:\plot\broken

file: XXXXXXXX_303269102_6848_6848  checked - OK

20:46:00: **creepMiner 1.7.16 Windows x64**
20:46:00: Release mode -CUDA -OpenCL +SSE4 +AVX +AVX2
20:46:00: ----------------------------------------------
20:46:00: Github:   https://github.com/Creepsky/creepMiner
20:46:00: Author:   Creepsky [creepsky@gmail.com]
20:46:00: Burst :   BURST-JBKL-ZUAV-UXMB-2G795
20:46:00: ----------------------------------------------
20:46:00: Changed logfile path to
20:46:00:       creepMiner_20180225_204600.782723.log
20:46:00: Found an invalid plotfile, skipping it!
**20:46:00:       Path: C:\plot\broken\XXXXXXXX_303269102_6848_6848
20:46:00:       Reason: The plotfile is incomplete!**
20:46:00: Config file loaded: mining.conf
20:46:00: Submission Max Retry : 3 seconds
20:46:00: Buffer Size : 4096 (4 GB)
...
20:46:00: Total plots size: 0.00 MB
20:46:00: Mining intensity : 12
20:46:00: Max plot readers : 0
20:46:00: Get mining info interval : 1 seconds
20:46:00: Processor type : CPU
20:46:00: CPU instruction set : AVX
20:46:00: Looking for mining info...

**Comment by Gapkobob** [comment]
Hey creepsky! Could you reupload 1.7.15?

**Comment by amiller2k17** [comment]
could your antivirus software be locking the plot file?

**Comment by Have-a-question-about-this-project** [comment]
I don't think so. The machine with that file is running windows defender. I have 187 other plot files that don't have an issue.
How are you deciding its incomplete? Are you doing it the same way as xplotter? 
Have you tried running it yourself to create a plot file the same size? I'm guessing its an edge case based on the number of nonces.

**Comment by Creepsky** [comment]
XPlotter is writing into a hidden alternative stream file, to remember the current number of wrote nonces.
Sometimes, for example if you cancel the XPlotter while writing or it crashes, the alt stream file gets messed up a bit.
creepMiner checks this file if it exists (only NTFS) and then throws an error, if the number of nonces inside of it doesn't match with the number extracted from the name of the plot file.
If I remember right, alternative stream files are not bound to a location, like real files are. They live in a global context. So even if you re-create the plot file in a different location, you will still get the same error, because the alt stream file is still messed up.

You can however work around this problem by either creating a new plot file with slightly different parameters (for example add 1 nonce; and this time don't stop the creation process), or activate `"useInsecurePlotfiles" : true` inside the config file.
Both will work, both has up- and downsides.

**Comment by nitr8** [comment]
Closing this case as Creepsky provided a valid workaround, even thou this is not a miner issue but an issue related to your plot file.
