### ISSUE TITLE
GPU mining not available in latest release 1.7.16?

### ISSUE THREAD

**Issue by themurph2k** [Creepsky/creepMiner#339]

**Comment by nitr8** [comment]
Hiya,

Same as last ticket, please provide the following:

- describe the problem as accurately as possible
- describe all steps to get to your problem so it can be traced - otherwise it is nearly impossible to fix it!
- provide additional information like the name of your **OS**, the miner **version**, your **gcc version**, ...
- attach **log files**, **screenshots** and your **config-file**

**Comment by cowboyjunkie** [comment]
The files that are hosted on Github to download for the 1.7.16 where never complied with gpu enabled for people who want to use the GPU feature for processing.  It was only compiled as a CPU only version.  I personally have tried to compile it, but keep getting errors on windows and gave up.  I have attached a pic of the startup showing that GPU is not enabled and this is the zip file pulled directly from github for the 1.7.16 version.  Also if I use the installer for windows I am getting the same version with out the GPU compiled in it.

![image](https://user-images.githubusercontent.com/9989750/37256493-c6c5c8a6-2531-11e8-8377-130916fd0b06.png)

**Comment by themurph2k** [comment]
Win10 v1709
AMD Adrenaline Drivers v18.2.3
GPU mining is not enabled for 1.7.16, only CPU mining

**Comment by Creepsky** [comment]
1.7.16 is not compiled with Cuda or OpenCL.
I changed to an automatic compilation process, but plan to add back Gpu support in future releases.

**Comment by Have-a-question-about-this-project** [comment]
When are you planning on doing the next release with GPU support?

**Comment by nitr8** [comment]
closing as this is resolved in 1.7.17
