### ISSUE TITLE
Web server does not update on latest Firefox in 1.7.6

### ISSUE THREAD

**Issue by themurph2k** [Creepsky/creepMiner#340]

**Comment by nitr8** [comment]
Hi themurph2k,

Could you give us some more information please? As per when opening ticket:

- describe the problem as accurately as possible
- describe all steps to get to your problem so it can be traced - otherwise it is nearly impossible to fix it!
- provide additional information like the name of your **OS**, the miner **version**, your **gcc version**, ...
- attach **log files**, **screenshots** and your **config-file**

**Comment by themurph2k** [comment]
Win10 v1709
Firefox Quantum v58.0.2 (64-bit)
The web interface for creepminer v1.7.6 does not update in Firefox. It works fine in Chrome and Edge.

**Comment by nitr8** [comment]
works fine in FF/Chrome/IE/Safari in 1.7.17

As this is not an issue in the latest builds, I will take the liberty of closing this case.
