### ISSUE TITLE
webserver ssl: SSL_ERROR_NO_CYPHER_OVERLAP

### ISSUE THREAD

**Issue by gitoriu** [Creepsky/creepMiner#390]
OpenSSL 1.0.1t  3 May 2016

openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout creepMiner.key -out creepMiner.crt

webserver starts with the configured certificate, but firefox can't connect and gives the following error:
SSL_ERROR_NO_CYPHER_OVERLAP

**Comment by nitr8** [comment]
@gitoriu  - May I suggest googling SSL_ERROR_NO_CYPHER_OVERLAP - guess you need a firefox update.  I have tested this with proper certs and it works 100%

There could also be issues with security and localhost certs. I wrote an article about this, its outdated so will need to be taken with a pinch of salt :) https://blog.nfye.com/create-your-own-self-signed-certificate-with-subject-alternative-names-using-openssl/

Using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. We have a great discord to ask for help here: https://discord.gg/qnjyVQt

Before submitting your issue, please review the following checklist:

- [ ] **DO** include log files.
- [ ] **DO** include the miner config.
- [ ] **DO** describe the operating system for the Server and Client (Windows / Linux). Also, the run-time platform and versions


### Subject of the issue
Describe your issue here.

### Your environment
* version of creepMiner
* version of OS
* which browser and its version

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead
