### ISSUE TITLE
Dual GPU OPENCL lock up on Windows 10

### ISSUE THREAD

**Issue by chrisf4lc0n** [Creepsky/creepMiner#404]
Windows 10 x64
GPU 1 RX480
GPU 2 R7 250

While plotting with Turbo Plotter 9000 or GPUPlotter using the RX480 I cannot mine using OPENCL on the R7 250, the miner starts the scan but always gets stuck randomly.
While using the jMiner problem does not exist.

**Comment by nitr8** [comment]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. 
Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. We have a great discord to ask for help here: https://discord.gg/qnjyVQt
- [ ] **DO** include log files.
- [ ] **DO** include the miner config.
- [ ] **DO** describe the operating system for the Server and Client (Windows / Linux). Also, the run-time platform and versions.


### Subject of the issue
Describe your issue here.

### Your environment
* version of creepMiner.
* version of OS.
* which browser and its version.

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behavior
Tell us what should happen.

### Actual behavior
Tell us what happens instead.


### Other information
List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to fix etc.
```
insert the output from ionic info here.
```
