### ISSUE TITLE
Segmentation fault caused by additional HDD Data, 1.8.1, Linux

### ISSUE THREAD

**Issue by BurnMe2** [Creepsky/creepMiner#407]
Hi,

i got some issue during testing 1.8.1 The Miner closed after starting with the information:
" Segmentation fault "

I figured out that there was one HDD with additional Data (3 Plotfiles and 1 Zip file) which caused this issue. After deleting the additional zip file the CreepMiner startet fine with any error message.

Don't know if this is a bug but for those who  get Segmentation fault message (in Linux) check your Plot Folder it seem there should be no other files in there than the plotfiles. (The older CreepMiner was working without warning segmenation fault)

**Comment by Beddhist** [comment]
I can confirm this on both Linux and Windows.

**Comment by nitr8** [comment]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. 
Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. We have a great discord to ask for help here: https://discord.gg/qnjyVQt
- [ ] **DO** include log files.
- [ ] **DO** include the miner config.
- [ ] **DO** describe the operating system for the Server and Client (Windows / Linux). Also, the run-time platform and versions.


### Subject of the issue
Describe your issue here.

### Your environment
* version of creepMiner.
* version of OS.
* which browser and its version.

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behavior
Tell us what should happen.

### Actual behavior
Tell us what happens instead.


### Other information
List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to fix etc.
```
insert the output from ionic info here.
```
Whats not clear about that?  closing this as there is a similar task when disconnecting a drive.
