### ISSUE TITLE
Segmentaton fault Ubuntu 14.04

### ISSUE THREAD

**Issue by DonVito7** [Creepsky/creepMiner#416]
Linux burst 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
------------------------------------------------------------------------------------------------------------------------------------------
Jun 24 18:41:49 burst kernel: [ 4532.669860] perf: interrupt took too long (2517 > 2500), lowering kernel.perf_event_max_sample_rate to 79250
Jun 24 18:41:59 burst kernel: [ 4542.169202] perf: interrupt took too long (3152 > 3146), lowering kernel.perf_event_max_sample_rate to 63250
Jun 24 19:51:57 burst kernel: [ 8740.704174] creepMiner[6397]: segfault at 108 ip 00007ff4c649dd44 sp 00007ff4c09412f0 error 4 in libpthread-2.23.so[7ff4c6494000+18000]
Jun 24 20:01:46 burst kernel: [ 9329.009538] creepMiner[6708]: segfault at 108 ip 00007f7ca21acd44 sp 00007f7c8563b2f0 error 4 in libpthread-2.23.so[7f7ca21a3000+18000]

**Comment by nitr8** [comment]
Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. 
Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. We have a great discord to ask for help here: https://discord.gg/qnjyVQt
- [ ] **DO** include log files.
- [ ] **DO** include the miner config.
- [ ] **DO** describe the operating system for the Server and Client (Windows / Linux). Also, the run-time platform and versions.


### Subject of the issue
Describe your issue here.

### Your environment
* version of creepMiner.
* version of OS.
* which browser and its version.

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behavior
Tell us what should happen.

### Actual behavior
Tell us what happens instead.


### Other information
List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to fix etc.
```
insert the output from ionic info here.
```
