### ISSUE TITLE
cannot get block infor when mining on 100-0 pool

### ISSUE THREAD

**Issue by taulzhu** [Creepsky/creepMiner#421]
tool: creepMiner-1.8.2.0-win64
pool: 100-0-pool.burst.cryptoguru.org:8124
log:
[creepMiner_20180701_043253.343371.log](https://github.com/Creepsky/creepMiner/files/2152419/creepMiner_20180701_043253.343371.log)

config:

**Comment by taulzhu** [comment]
[mining.conf.txt](https://github.com/Creepsky/creepMiner/files/2152423/mining.conf.txt)

**Comment by nitr8** [comment]
You have not specified your wallet information.

Closing this before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. 
Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. We have a great discord to ask for help here: https://discord.gg/qnjyVQt
- [ ] **DO** include log files.
- [ ] **DO** include the miner config.
- [ ] **DO** describe the operating system for the Server and Client (Windows / Linux). Also, the run-time platform and versions.


### Subject of the issue
Describe your issue here.

### Your environment
* version of creepMiner.
* version of OS.
* which browser and its version.

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behavior
Tell us what should happen.

### Actual behavior
Tell us what happens instead.


### Other information
List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to fix etc.
```
insert the output from ionic info here.
```
