### ISSUE TITLE
CL_INVALID_KERNEL_ARGS

### ISSUE THREAD

**Issue by Integrative** [Creepsky/creepMiner#427]
Running CM 1.8.2 on Ubuntu 16.04LTS with AMD 17.5 OpenCL
GPU is AMD Rx570-4GB (Dedicated to miner, display GPU is Intel onboard)

OpenCL implementation is fine, XMR or ETH miner can run for days without any issues.

Mining runs for a couple of hours, then crashes and throws 

hh:mm:ss: Error while verifying a plot file!                                                                                                                                                                
hh:mm:ss: 	Error: CL_INVALID_KERNEL_ARGS

Looked at issue 219, replaced mining.cl with 'old' version, but seems same as one that comes with 1.8.2, makes no difference

Any ideas?

**Comment by nitr8** [comment]
Hi Integrative, yes read this when opening a issue request:

Before submitting your issue, please review the following checklist:

- [ ] **AVOID** using the issue tracker for questions or help. 
Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. We have a great discord to ask for help here: https://discord.gg/qnjyVQt
- [ ] **DO** include log files.
- [ ] **DO** include the miner config.
- [ ] **DO** describe the operating system for the Server and Client (Windows / Linux). Also, the run-time platform and versions.


### Subject of the issue
Describe your issue here.

### Your environment
* version of creepMiner.
* version of OS.
* which browser and its version.

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behavior
Tell us what should happen.

### Actual behavior
Tell us what happens instead.


### Other information
List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to fix etc.
```
insert the output from ionic info here.
```
