### ISSUE TITLE
ipv6 work but not work, but work

### ISSUE THREAD

**Issue by Pascal66** [Creepsky/creepMiner#44]
**_Work because ipv6 detected (Wonderfull, you are the first miner to allow that):_**
10:37:01: Pool Host : 127.0.0.1:8124 (fe80::6c9f:1b0c:89ce:1e3c%18)
10:37:01: Mininginfo URL : 127.0.0.1:8124 (fe80::6c9f:1b0c:89ce:1e3c%18)
**_Dont work because unknown protocol :_** 
10:37:01: could not send request to host: unknown protocol !
10:37:01: uri:
**_Work because nonce confirmed :_** 
10:41:45: V4W6-A7MW-9P3R-CEAYM: nonce confirmed (0d 12:57:18)
10:42:23: plot list reader finished reading plot-dir Y

**Comment by Creepsky** [comment]
Can you please post your *-URLs (poolUrl, miningInfoUrl, walletUrl) from the configuration file?

**Comment by Pascal66** [comment]
Sure. 
poolUrl = miningInfoUrl =walletUrl = 127.0.0.1

**Comment by Creepsky** [comment]
Try explicitly set the whole url: poolUrl = miningInfoUrl = walletUrl = "http://127.0.0.1:8124".
URLs normally looks like this 
```
<scheme>://<host>:<port>
```

Nonetheless I will add an implicit conversion to a valid URL so you can set it to `127.0.0.1` and the miner will convert it to `http://127.0.0.1:<default port>`.

**Comment by Pascal66** [comment]
Seems not the problem @Creepsky. I've no problem with the url scheme, it work and allow IPv6. 
The only line wich made me perplex is : 
```
 10:37:01: could not send request to host: unknown protocol !
 10:37:01: uri:
```

**Comment by Creepsky** [comment]
These two lines should show you the url to which the miner wants to connect but can't because of an unknown protocol.

The code looks like this

```
std::string("could not send request to host: unknown protocol ") + uri_.getScheme() + "!",
    std::string("uri: " + getCanonical())
```

```
... getCanonical(...) ...
{
	return ... uri_.getHost();
}
```

So the problem here is that **uri_.getScheme()** and **uri_.getHost()** gives us an empty string.
My guess is that your wallet url is somehow not properly set. Do you get informations about the last winner?
Another hint for an invalid wallet url is that your numeric account id don't get translated to your name:
10:41:45: V4W6-A7MW-9P3R-CEAYM: nonce confirmed (0d 12:57:18).

 Can you please copy paste the whole lines for the urls like this:

    "poolUrl" : "http://pool.burstcoin.biz:8124",
    "miningInfoUrl" : "http://pool.burstcoin.biz:8124",
    "walletUrl" : "https://wallet.burst-team.us:8127",

Another thing you could do is looking at the local webserver.
Just set "Start Server": true and "serverUrl" : "http://192.168.0.1:80" or your desired url.
Then in your browser go to this address and look in the "System"-tab. What's written there?
