### ISSUE TITLE
Linux ARM version

### ISSUE THREAD

**Issue by rotzbouf** [Creepsky/creepMiner#78]
Is it possible to include ARM support for the miner to run it on devices like the Raspberry Pi / Banana Pi / Odroid / etc?

**Comment by Creepsky** [comment]
In theory it should be possible.. the Poco library is ARM ready, but don't know if all of the miners code is ARM compatible. Have to find it out.

**Comment by misovan** [comment]
For the sake of curiosity I tried to build it on Raspberry. POCO went fine, but after trying the miner I got

`burstcoin@raspberrypi:~/Miner/creep_miner/creepMiner-2.4.5 $ make
g++ -O3 -march=native -std=c++14 -Wall -D_REENTRANT -DNDEBUG -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/sphlib/sph_shabal.cpp -o bin/obj/sphlib/sph_shabal.o
*** Error in `g++': double free or corruption (top): 0x01cde4c8 ***
Makefile:41: recipe for target 'bin/obj/sphlib/sph_shabal.o' failed
make: *** [bin/obj/sphlib/sph_shabal.o] Aborted
`

**Comment by Creepsky** [comment]
What is your ```gcc --version```?
Found this [topic on the rapsberry pi forums](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=139091).
Seems like you have to replace ```-march=native``` with your raspberry pi architecture ([have a look at this](https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html)).
Would be nice if you could test it, I don't own a Raspberry Pi.

**Comment by rotzbouf** [comment]
Hi,

Sorry for late reply. I was on duty last night and got a callout.
So my gcc version is this:
gcc (Raspbian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I will try to modify the -march flag and see what it gets.

Anyhow, thanks for the help

**Comment by rotzbouf** [comment]
I got the same error like you when compiling with -march=armv7.
Now I tied with -march=armv7ve and it seems to compile at least.

will keep you updated

**Comment by Pascal66** [comment]
An Arm version can be possible for now. WIthout hdd.

**Comment by rotzbouf** [comment]
The compile finishes without error but when I start up the binary I get the
below error message:
pure virtual method called
terminate called without an active exception
Aborted

No further info given in the output.

**Comment by Creepsky** [comment]
It seems that the ARM version of libc++ has a bug in std::thread, what causes the error.
Is there any chance that you can compile the miner with a newer gcc (5, 6)?
Here is a good [tutorial for gcc-6](https://solarianprogrammer.com/2016/06/24/raspberry-pi-raspbian-install-gcc-compile-cpp-14-and-cpp-17-programs/) without overwriting the old one.

**Comment by misovan** [comment]
Tutorial looks good even not w/o risks to my Rasperry :) I'll give it a try when back to home

**Comment by Creepsky** [comment]
Please don't do it if you are not sure !! Don't want that you hate me afterwards :P
Maybe I try to setup a virtual Raspberry Pi.

**Comment by misovan** [comment]
Well, I tried it after installing gcc-6. I tried both with -march=native and -march=armv8-a. it does start indeed, but then immediately fails:

```
burstcoin@raspberrypi:~/Miner/creep_miner/creepMiner-2.4.5 $ make CC=gcc-6
gcc-6 -O3 -march=native -std=c++14 -Wall -D_REENTRANT -DNDEBUG -Isrc/sphlib -Isrc/nxt -Isrc -IPoco/Net -IPoco/Foundation -IPoco/NetSSL_OpenSSL -IPoco/openssl -IPoco/Crypto -IPoco/Util -IPoco/JSON -c src/MinerLogger.cpp -o bin/obj/MinerLogger.o
In file included from src/MinerLogger.cpp:9:0:
src/MinerLogger.hpp:15:26: fatal error: Poco/Channel.h: No such file or directory
 #include <Poco/Channel.h>
                          ^
compilation terminated.
```

**Comment by Creepsky** [comment]
Did you try it with ```make CC=g++-6```?
Its the same compiler, but with some extra macros and libs.

**Comment by misovan** [comment]
Yeah, did it yesterday with both options with the same result

**Comment by Creepsky** [comment]
He cant find Poco, what is a little bit strange.
I think you need to rebuild and install it with the new gcc. Here is the content of install_poco.sh combined with the new compiler:

```
#!/bin/sh
set -ex
wget https://pocoproject.org/releases/poco-1.7.6/poco-1.7.6-all.tar.gz
tar -xzvf poco-1.7.6-all.tar.gz
cd poco-1.7.6-all && ./configure --no-tests --no-samples && make CC=g++-6 && sudo ldconfig && sudo make install
```

**Comment by misovan** [comment]
I tried to recompile POCO as it was apparently not correct. It failed with new gcc. What I googled there are POCO binaries available for raspberrypi through apt-get however much older version (1.3 or so)... not sure it will help

**Comment by misovan** [comment]
OK I moved a little bit further. I was able to compile POCO using arm-linux-gnueabihf-gcc from git://github.com/raspberrypi/tools.git. In poco-1.7.6-all/build/config I updated ARM-Linux config with 

`TOOL               = arm-linux-gnueabihf`

Poco libraries then compiled correctly, I have now Poco's *.so shared libraries in /usr/local/lib and all of *.h files in /usr/local/include/Poco.

Anyway when I try to compile creepMiner I still get undefined dependency errors and it fails:

```
g++-6 -O3 -march=native -std=c++14 -Wall -D_REENTRANT -DNDEBUG -o bin/creepMiner bin/obj/sphlib/sph_shabal.o bin/obj/nxt/nxt_address.o bin/obj/MinerLogger.o bin/obj/AccountNames.o bin/obj/PlotVerifier.o bin/obj/Miner.o bin/obj/Response.o bin/obj/Socket.o bin/obj/Request.o bin/obj/MinerConfig.o bin/obj/PlotGenerator.o bin/obj/Deadline.o bin/obj/NonceSubmitter.o bin/obj/Wallet.o bin/obj/MinerShabal.o bin/obj/PlotSizes.o bin/obj/MinerData.o bin/obj/RequestHandler.o bin/obj/PlotReader.o bin/obj/Declarations.o bin/obj/MinerServer.o bin/obj/MinerUtil.o bin/obj/Account.o bin/obj/main.o bin/obj/Url.o -L/usr/local/lib -pthread -lPocoFoundation -lPocoNetSSL -lPocoCrypto -lPocoUtil -lPocoNet -lPocoJSON

bin/obj/Response.o: In function `Burst::Response::receive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':

Response.cpp:(.text+0x860): undefined reference to `Poco::NestedDiagnosticContext::push(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char const*)...'



Response.cpp:(.text+0xba4): undefined reference to `Poco::Exception::displayText[abi:cxx11]() const'

```

I am not really geek in C++compiling so it might be some simple issue I am not able to figure out. However I was able to compile original uray's miner with g++-6 without issues (it just works in a quite strange way, giving deadlines in order of years to the pool... so perhaps outdated nowadays)

**Comment by misovan** [comment]
Adding to my previous post the full console output. If I understand correctly the output, build process fails after making all .o files, when it tries to make executable creepMiner.

[creepMinerMakeLog.txt](https://github.com/Creepsky/creepMiner/files/805146/creepMinerMakeLog.txt)

**Comment by Creepsky** [comment]
Thank you both for the effort you are putting into it.

The output says, that g++ can't find the poco library files (.so).
Maybe you just need to call ```sudo ldconfig```.

**Comment by misovan** [comment]
Thank you, I checked that possibility and learnt the stuff on the way - POCO .so libraries really look ok:

- installed in /usr/local/lib
- there are both .so files with version numbers and symlinks to them libPocoXxx.so ->libPocoXxx.so.VERSION
- ld.so.conf includes usr/local/lib, I have rebuild the cache using ldconfig

Unfortunately getting still the same error...

**Comment by Dadadah** [comment]
An update on this for you. I was playing around with my pi trying to set up creep. I discovered that the problem was poco itself because I tried to compile another program that used poco and I was unsuccessful. Same errors. I installed the 1.7.8 version and the program successfully make'd. It did not run but I think I forgot to run ldconfig. I will do that tomorrow and let you know the result.

**Comment by Dadadah** [comment]
After running sudo ldconfig, creepminer has loaded successfully.

**Comment by Creepsky** [comment]
That are good news, thanks for sharing.
What exactly was the problem with poco and how did you solve it?
Would be really nice if you could shortly summarize your build-steps for other pi users.

**Comment by Dadadah** [comment]
I'm not sure what the problem was with PoCo. It built successfully and it also installed to the correct location (/usr/local/lib) but for some reason GCC/G++ was not creating executables with PoCo. I simply downloaded the 1.7.8 version, built it, and Creep was able to run.

A few notes:
I changed my apt-get from Debian Jessie to Debian Stretch. This allowed me to install gcc/g++ 6.
I overrode the default g++ with g++-6
I configured PoCo with the following:
./configure --no-samples --omit=Data/ODBC,Data/MySQL
sudo make install
then called
make
on the creepminer directory.

**Comment by misovan** [comment]
Interesting that you got it working.
I have run updated install-poco.sh on my pi (I changed the poco version to 1.8 and added CC=g++-6 after make), but it ended with an error:

`src/adler32.c:65:25: error: ‘uLong adler32_z’ redeclared as different kind of symbol
 uLong ZEXPORT adler32_z(adler, buf, len)
                         ^~~~~
In file included from src/zutil.h:22:0,
                 from src/adler32.c:8:
src/zlib.h:1707:23: note: previous declaration ‘uLong adler32_z(uLong, const Bytef*, z_size_t)’
 ZEXTERN uLong ZEXPORT adler32_z OF((uLong adler, const Bytef *buf,
                       ^~~~~~~~~
src/adler32.c:65:25: error: ‘adler’ was not declared in this scope
 uLong ZEXPORT adler32_z(adler, buf, len)
                         ^~~~~
src/adler32.c:65:32: error: ‘buf’ was not declared in this scope
 uLong ZEXPORT adler32_z(adler, buf, len)
                                ^~~
src/adler32.c:65:37: error: ‘len’ was not declared in this scope
 uLong ZEXPORT adler32_z(adler, buf, len)
                                     ^~~
src/adler32.c:69:1: error: expected unqualified-id before ‘{’ token
 {
 ^
/home/burstcoin/Miner/creep_miner/creepMiner-2.6.0/poco-1.7.8-all/build/rules/compile:61: recipe for target '/home/burstcoin/Miner/creep_miner/creepMiner-2.6.0/poco-1.7.8-all/Foundation/obj/Linux/armv7l/debug_shared/adler32.o' failed
make[1]: *** [/home/burstcoin/Miner/creep_miner/creepMiner-2.6.0/poco-1.7.8-all/Foundation/obj/Linux/armv7l/debug_shared/adler32.o] Error 1
make[1]: Leaving directory '/home/burstcoin/Miner/creep_miner/creepMiner-2.6.0/poco-1.7.8-all/Foundation'
Makefile:131: recipe for target 'Foundation-libexec' failed
make: *** [Foundation-libexec] Error 2
`

**Comment by remac-lkr** [comment]
Hi folks,

I got the Miner up and running on the Raspberry Pi 3 Model since yesterday and actually got a few nonces confirmed (right now still mining with 90GB but plotting another 600GB).
I installed Poco like explained in [Compilation & Installation / Poco on Linux](https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation#poco-on-linux) which went great but I stumbled across the *** Error in g++': double free or corruption (top): …. ***-Error after using `make`. I got around it by, like @Creepsky and @rotzbouf mentioned, changing the `-mach=native` to `-mach=armv6` in the Makefile under CFLAGS. Now it should be possible to compile the miner by `make`.
Furthermore I changed the run.sh-File to: 
`#!/bin/sh`
`export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"`
`./creepMiner`

Before starting the miner I used `sudo ldconfig` just like @Dadadah. Seems like you should do this after adding new libraries like Poco...
Now you can go into the bin-folder inside the creepMiner-folder and start the Miner.

I would be glad to hear if you got it working now. :-)

Nice Evening/Day

Sources:
https://github.com/dpayne/cli-visualizer/issues/27
https://github.com/OpenRTMFP/Cumulus/issues/17
http://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s

**Comment by de-luxe** [comment]
Writing a little guide/field report on forums.burst-team.us would be awesome. I would like to see pictures, too.

**Comment by remac-lkr** [comment]
Pictures of the installation process or the running miner? 
For now I made a screenshot of the running miner yesterday with a confirmed nonce.
I think I will write a guide or field report on forums.burst-team.us at the weekend but I will link it here when it's done.
![confirmed nonce](https://cloud.githubusercontent.com/assets/28687323/26103829/8b20974a-3a3b-11e7-9630-52281fda12e6.jpeg)

**Comment by misovan** [comment]
Finally, I have got Poco compiled and then quickly got the miner working :-) I am surprised how efficient it is. It scans 100 GB plotfile from HDD docked in standard NAS and connected as a samba share through home router in roughly 2s.

For anybody playing with it using pi as a screen-less server I recommend to run the miner using screen utility. It allows to let the miner run in background session, being able to close any connections to the pi (putty or vnc session). [Basic usage for this use case is here](http://raspi.tv/2012/using-screen-with-raspberry-pi-to-avoid-leaving-ssh-sessions-open). You can then monitor the miner using simple web console (Start server setting in miner conf).

Thanks to all for your help.

**Comment by DCayee** [comment]
Guys, could you help me run the miner on raspberry?
I tried to follow the steps but I couldn't make it work.
Can anyone make a video or a more detailed tutorial from the beginning? Thanks!
Cheers!

**Comment by misovan** [comment]
Hi, DCayee, did you follow the steps [described on wiki page](https://github.com/Creepsky/creepMiner/wiki/Compilation-&-Installation-on-the-Raspberry-Pi-3)?

What finally worked for me was to install latest POCO version (v1.7.x simply did not work for me, so I updated install_poco.sh to download latest version). Then I compiled creepMiner with small change to makefile as written in the wiki.

**Comment by DCayee** [comment]
Hi, misovan.

I've tried what remac-lkr said but I hadn't seen this wiki.
I'll try again today!
How many TBs are able to read with a Pi3?

cheers!

**Comment by wow1888** [comment]
Will this do the plotting as well?  If not is there software that works on the raspberry pi for that piece?

**Comment by Creepsky** [comment]
@wow1888 only mining, but I think you can use every Linux plotter like [mdcct](https://github.com/Mirkic7/mdcct).

**Comment by TssTEntertainment** [comment]
I have successfully get it to run on my Pi2, but there is no plot I get this message:
...
Total plots size: 0.00 MB
...

Have I forgot to initialize something ?

**Comment by TssTEntertainment** [comment]
without mount I get this message:
...
Plot file/dir does not exist: '/media/hdd/plots/'
Total plots size: 0.00 MB
...

So he know the directory.
So it must be that I have forgot to initialize something ?

**Comment by Adavan83** [comment]
Hello @TssTEntertainment.
Please post content of directory "/media/hdd/plots/". You can use command "ls -la".
Thank you.

**Comment by TssTEntertainment** [comment]
content of directory "/media/hdd/plots":
total 8
drwxr-xr-x 2 root root 4096 Jun 14 05:55 .
drwxr-xr-x 4 root root 4096 Jun 14 05:55 ..

**Comment by Adavan83** [comment]
... and where is your plotfiles? ;)

I have something like this:
```
burst@burst:~/mount/plotH$ ls -la
celkom 302080056
drwxrwxr--  3 burst burst         4096 máj 15 15:58 .
drwxr-xr-x 13 root  root          4096 máj 27 12:16 ..
drwxrwxr--  2 burst burst        16384 jún 27  2016 lost+found
-rw-r--r--  1 burst burst 309329920000 máj 15 19:27 12066338979942611474_17940007_1180000_20000
```
You can see my plot file with name "12066338979942611474_17940007_1180000_20000" and have about 309GB size.
So, "plotH" is root directory of device "sdj", as you can see below (i shrink the list, because in my rig i have many drives):
```
burst@burst:~/mount/plotH$ sudo mount
[sudo] password for burst: 
xxx
/dev/sdh1 on /home/burst/mount/plotJ type ext4 (rw,noatime,data=ordered)
/dev/sdj1 on /home/burst/mount/plotH type ext4 (rw,noatime,data=ordered)
/dev/sdk1 on /home/burst/mount/plotI type ext4 (rw,noatime,data=ordered)
xxx
```
I have easy strategie - one plot file on each root drive, root drive is mounted to one directorie and each directories are placed in config for miner.
In config file (default "mining.conf") you must tell miner, where is stored plot files. In my case, i mount all drives throught fstab and in mining.conf i have defined all this directories.

Now it is on you and your strategie, how you store your plot files. In linux you have many choices and depend on you and your environment.

**Comment by TssTEntertainment** [comment]
oh thanks,
how can I create a plot ?

**Comment by misovan** [comment]
@wow1888 - I think trying to plot using pi makes not too much sense - it is a resource intensive task. I did my plots using intel core i7 with nvidia graphics laptop, it still took ages to complete.

Mining itself can be done with pi more as a study work then for any tangible gain. I let my pi mine on 2x2TB HDDs sitting in a dock connected through USB cable - so in total cca 3.7TB plots. Scanning for deadlines through 2 HDDs takes my pi around 60-70s, I would not go for more on one pi. I use another USB flash stick to store logs. The advantage is that it is very stable, low power setup running few weeks for me without any issue. Moreover I do not burn my windows laptop - they are not designed for 24/7 run.

**Comment by Adavan83** [comment]
As @Creepsky wrote, you must use "plloter" to create a plot file. Miner use plot file as a "dig site". You can have many of plot files.
Your questions are very beginner ;). Please look on this [video](https://www.youtube.com/watch?v=cVIhqKUdve8). It is for Windows, but you reach knowledge about BurstCoin mining process.
In next step download "mdcct" package (link see above).
After compiling here you can spot CPU plotter. Again depends on your environment, that is possible use AVX instruction or not. In this package you also have "readme" file about controlling plloter.
Please keep on mind, that ploting process cost many of resources of your computer and cost many of time! Maybe you should use for plotting different computer, with more computing power.

**Comment by TssTEntertainment** [comment]
ok thanks @misovan and @Adavan83  now I am understand how it works.

**Comment by TssTEntertainment** [comment]
For test I have now 25GB plot and the Pi2 recognised it.
But I don't think he work properly.
I get this messages:

10:57:41: block#      370937
10:57:41: scoop#      1760
10:57:41: baseTarget# 512909
10:57:41: --------------------------------------------------
10:57:41: /mnt/md0/plots/12247052553232600039_0_102400_4096 (25.00 GB) read in 0.392s (~15.94 MB/s)
10:57:41: Dir /mnt/md0/plots/ read (1 files, 25.00 GB total) in 0.394s (~15.84 MB/s)
10:57:47: Got no response for wallet request '/burst?requestType=getAccount&account=2334715511295126722'
10:57:47: --------------------------------------------------
10:57:47: last block winner:
10:57:47: block#             370936
10:57:47: winner-numeric     2334715511295126722
10:57:47: winner-address     GD84-EEZ7-54CP-4MNT2
10:57:47: --------------------------------------------------

mabey wrong time ?

**Comment by Adavan83** [comment]
If you mine on some pools, check, if pool see your miner.
Another reason should be, that complexity is out of your options :(. I have small 5GB plot and sometimes not confirm nuance. You must check it in long period, that sometimes you got nuance.

**Comment by jeev20** [comment]
@Creepsky @remac-lkr @Dadadah @misovan you guys are Awesome! The miner works well on my RPI3. I get read speeds of upto 32 mb/s with a 1.5 tb plot on my external HDD.  Thank you for your help and the wiki page. Followed instructions as you recommended.  
However, I observed that some blocks are not reported (skipped) in the miner or the reporting is delayed over a minute or so. By the time miner picks up the block the next block would start.  I cross checked this with the pools block explorer.  Any idea what may be the reason for these skips and delays in discovering new blocks? Wifi connection seems to be stable. Thanks again

**Comment by DCayee** [comment]
Hey guys, 
I am sorry for the delay, but it was a little busy the last few days...
I think now I'm minning through Pi3!!

I changed the location plots to "/media/pi/caye_cloud_3/Burst_plots" and everything is working fine.

I just wanna know how do I change the pool...
The default is burst-team-us, but I would like to mine with burst.lexitoshi.uk/
What should I change in mining.conf ? (what should I put in miningInfo, submission and wallet?)

Thanks for the help!
Cheers!

**Comment by Creepsky** [comment]
@jeev20 what do you mean by blocks skipped? Is the miner skipping them completely or is it mining but yout just dont get a good deadline? The miner checks every 3 seconds for a new block. Did you try using a cable instead of wlan?

@DCayee you have to change 2 things:
1. your reward assignment (https://wallet.burst-team.us:8128/rewardassignment.html; change https://wallet.burst-team.us:8128 to whatever wallet you use)
fill in your passphrase + `BURST-F3XD-Y4M5-SN8C-G9FFJ` in recipient
![rewassig](https://user-images.githubusercontent.com/8005422/27371785-6b048a78-5662-11e7-933f-6674d82afe6c.PNG)
2. in your config file: set `mining.urls.miningInfo` and `mining.urls.submission` to http://burst.lexitoshi.uk:8124

**Comment by DCayee** [comment]
Thanks. I'll try to chance the configurações file tonight!

**Comment by wow1888** [comment]
@DCayee Just curious if you used the Pi3 to actually plot the files? If so what program did you use?  The ones I've tried don't work due to the 64 bit limitation

**Comment by jeev20** [comment]
@Creepsky  That is right. The miner skips multiple blocks (even blocks which have life of 10 minutes or more). It starts working again after about 4 to 6 blocks with equal number of "Could not get blocks info" error messages. I am not sure what happens. When I check the pool, I see the new blocks generated, while the miner does not update (no reads and no deadlines). Some times the miner skips blocks for almost an hour before starting again. I have attached two images. 
![blocksnotfound](https://user-images.githubusercontent.com/19647823/27406147-4ca3879c-56d4-11e7-8ebc-8adf07526cc7.png)
![blocks skipped](https://user-images.githubusercontent.com/19647823/27406158-54491a48-56d4-11e7-9647-a59dd86a598d.png)


Since I only have access to a Wlan, I have not tired to use lan cable . 

It is impressive that the read speeds during mining now range from 29 to 40 mb/s on RPI3, which is 4 times faster than my Intel i7 pro, 16gb RAM laptop on a USB 3 connection ! Thanks again!

**Comment by Creepsky** [comment]
@jeev20 this really sounds like a hardware issue for me.
Is there something suspicious in the log files between the "could not get block infos" errors and the next block?

**Comment by rattle99** [comment]
@jeev20 The read speeds of raspberry Pi 3 are impressive indeed. I am getting just 2.5mb/s on the Pi 1 Model B+, which filesystem are you using? Is it ext4?

**Comment by jeev20** [comment]
@Creepsky You are right. After I placed the RPI close to the Wifi router, I did not get any "Could not get blocks info" error messages. I have run the miner for two nights now without any critical issues.  
I am setting up the miner on a Pi Zero V3 now, will let this forum know how it went. My plan is to have a powered USB hub to power the HDDs and connect them to the RPI Zeros USB input. Not too optimistic about the read speeds, but could be great for power savings. 

@rattle99  Yes, I was surprised too. I am not sure, but I think it is because I changed the maxbuffersizeMB from 128 to 512 in the mining.config.  The HDD (WD Elements 2 TB) is in the stock setting of NTFS file system.

**Comment by Velocitus** [comment]
Hello,
with described tips I managed to run creepminner on A20-olinuxino-lime board with Debian Jessie OS. ( a single-board PC with SATA port ). Few things I'd like to point out :
- PoCo libraries downloaded via install script didn't contain "Crypto" folder so I had to manually install latest 1.7.8p3 version from "pocoproject". (The compillation took solid 6 hours.)
- being armv7 architecture I had to set `-march=native`
- `sudo ldconfig` is necesary

Everything else went relativle well for 32bit system with 512MB RAM (everything takes ages).
Low speed is price for low system power consumption, which including old 320GB Seagate drive salvaged from notebook, is 3.2W at idle and 4.6W while scanning the drive. Device also has Li-ion backup system making it very efficient and reliable miner. Disk read speed are a bit of an issue as they are 17MB/s on average via the SATA port. They were about 13MB/s with the drive connected via USB converter. Testing the same plotted drive on desktop PC via SATA resulted in speeds around 30MB/s. Any tips for improving the speed? I've tried changing power management settings with `hdparm` and driver with `ntfs-3g`. They made about 2MB/s improvement.

**Comment by Pengo-fmm** [comment]
Hi,
I am getting stuck during the compilation, I tried updating to the latest version of Poco, but nothing changes.
After I launch the compilation with make I get the error:

src/Url.hpp:4:22: fatal error: Poco/URI.h: No such file or directory
 #include <Poco/URI.h>
                      ^
compilation terminated.
Makefile:41: recipe for target 'bin/obj/Url.o' failed
make: *** [bin/obj/Url.o] Error 1

can someone please help?
Thanks!

**Comment by StianCronje** [comment]
I'm having the same problem as @Pengo-fmm. I installed g++-6, used the latest version of POCO, and followed all the instructions from the Pi compilation Wiki. 
Does anyone know how to fix this?
Thank you for your help.

**Comment by StianCronje** [comment]
I am using a raspberry pi 2. I tried making with march=native and it worked. I used the install-poco.sh from the 1.6 release and all the other files from the current source code.

Thanks @Creepsky for the great work
