### ISSUE TITLE
Forwarding broken since Commit 668948e (Reworked core)

### ISSUE THREAD

**Issue by exciler** [Creepsky/creepMiner#83]
Since 668948e Miner::getMiningInfo() expects "baseTarget" to be a string. This is true for at least my pool but MinerServer generates MiningInfo with baseTarget being numeric.

Simple fix is to replace extract by convert in Miner::getMiningInfo(). But I am not sure if baseTarget should be a string by design and the MinerServer has to be corrected.

**Comment by Creepsky** [comment]
Don't know why the pool is sending the baseTarget as a string, because in the end its just a plain number (64 bit unsigned int).
But your fix should work whatever the creepMiner will get as baseTarget from the pool - nice!

For other miners, the MinerServer needs to be corrected, just like you said. A simple std::to_string should do the work.

**Comment by Creepsky** [comment]
Found an interesting question on stackoverflow: http://stackoverflow.com/questions/10631494/json-parse-parses-converts-big-numbers-incorrectly.

This explains, why the basetarget is send as a string and not a number.
The JSON-parser from javascript handles all numbers as floats, and because of this there are rounding errors.

If you have a string, you don't lose significant bytes.
