### ISSUE TITLE
Forward nonce only if better than current deadline and vice versa

### ISSUE THREAD

**Issue by exciler** [Creepsky/creepMiner#85]
Some pools charge a fee for submissions that a worse than own best deadline.
Therefore it would be nice if creepMiner would combine the submissions from own mining and connected miners and only forward a request if no other miner (including itself) has already found a better deadline. 

Maybe a solution is a common filter for both submission types (ForwardHandler and NonceSubmitter)

**Comment by Creepsky** [comment]
Good point, but this is not as easy as it sounds.
The request for a nonce submission is ```/burst?requestType=submitNonce&nonce=123&accountId=123```.

So whats missing is the deadline, that must be reconstructed by creating a plot in RAM with the nonce and account-id as the parameters (there is a class called ***PlotGenerator*** for this, but it is not fully implemented).

It would be easy to add ```...&deadline=123``` to the request of the creepMiner, but I don't know how other miners are doing this.

So either we implement the PlotGenerator, or we make this miner dependant:

```
if (request has parameters deadline, nonce, accountId)
{
    await Miner::submitNonce
    send back result of Miner::submitNonce
    (Miner::submitNonce is handling the check for better deadlines)
}
else
{
    just forward it without checking
    and send back the result
    this can lead to a fee, like you said
}
```

Implementing the PlotGenerator is the safer solution, but is a lot of work (especially for CUDA).
Reuse Miner::submitNonce is the cleaner solution, but depends on the parameter ```&deadline=123```

What do you think about this? Any better ideas?

**Comment by Pascal66** [comment]
I think no pool at all, handle the case of &deadline=123 
The general rule is req.url = '/burst?requestType=submitNonce';
&nonce=... &accountId=... or &secretPhrase=...
Because the BurstServer itself request only that : 
[SubmitNonce](https://github.com/burst-team/burstcoin/blob/master/src/java/nxt/http/SubmitNonce.java)

**Comment by Creepsky** [comment]
Seems like [Blagos miner](https://github.com/Blagodarenko/miner-burst/blob/master/miner.cpp#L869)  is doing it on the same way (by adding the deadline query parameter), while the [jminer](https://github.com/de-luxe/burstcoin-jminer/blob/master/src/main/java/burstcoin/jminer/core/network/task/NetworkSubmitPoolNonceTask.java#L102) not.

So I think for now it's the best to proceed with the deadline parameter, handle full compatible requests with a "is-best-check" and forward all partially compatible requests (without the deadline parameter) without checking, just like in the pseudo-code I wrote.

@Pascal66 yup, the pool would not understand ```&deadline=123```, but thats fine. It's just for the forwarding miner, the pool does not need it.

**Comment by exciler** [comment]
I would go for the &deadline=123 way for now... it is easy in comparison with PlotGenerator and suffices if we can trust the other miner. Maybe just add an config parameter to allow deadline parameter. So it can be switched off if untrusted miners are connecting or all requests shall be forwarded.
When PlotGenerator is ready at some time it should be pretty easy to use it for requests without deadline parameter. Even with PlotGenerator the use of the deadline parameter has the advantage of not using any additional computing power.

**Comment by Creepsky** [comment]
Was a lot more work than I thought. But here is the first version of it: a88b5f2. I tested it with 1 forwarding creepMiner, 2 normal creepMiner and 1 Blago miner.

Unfortunately, ```&deadline=123``` was not possible, because Blagos miner sends ```deadline (in seconds) / basetarget```, while the creepMiner just transfers ```deadline (in seconds)```.

So I decided to create a new variable in the POST body: ```X-Deadline```. Also ```X-Plotfile``` shows in which plotfile the nonce was found.

The forwarding creepMiner handles the incoming forwarded deadlines/nonces as his owns, so it is possible to use the webserver and so on.

Maybe you can test it and say if something is wrong or should be changed: https://github.com/Creepsky/creepMiner/tree/forward-filter.
